### ISSUE TITLE
onButtonRelease vs onButtonPress

### ISSUE THREAD

**Issue by michaudg** [lestcape/Gnome-Global-AppMenu#100]
Is there a reason why the menus needs only a mouse button down to show instead of a mouse button click? It could be great to have the same click behavior that the rest of the desktop environment.

Wonderful extension and thanks for your work!

**Comment by lestcape** [comment]
Well, i don't think that the "click" behaviour it's the behaviour of the whole shell, but i know what you try to say, because yes all is different here, but what you want to say is "button-press" vs "button-release", but you say that just for menu-items that are not submenu-items.

The reason, is because the popup-menu API that is used is not the Shell popup-menu API. So, could work different as is not the same API that is used in the whole shell. I can not used the Shell API, because nothing of this will work with the shell API.

If your question is, if the API can work similar to the shell API, well, probably i can change the internal API to work similar of how is working the shell API, but a change like that could introduce more problems. It's not just easy as could affected other things.

Anyway i think you can play with this if you want: https://github.com/lestcape/Gnome-Global-AppMenu/blob/master/gnomeGlobalAppMenu%40lestcape/configurableMenus.js#L2055-L2063

For another point of view, why you considered that it's better the shell way than the current way? What is the conflict anyway?  For me is not much important this anyway.

**Comment by michaudg** [comment]
> but you say that just for menu-items that are not submenu-items.

Right!

> Anyway i think you can play with this if you want

Thanks a lot! Using `onButtonRelease` makes the menu-items behavior the same that the system menu and others shell extensions (Places status indicator, Removable drive menu, ...). I'm glad to see that the code is already included! :)

> For another point of view, why you considered that it's better the shell way than the current internal way? What is the conflict anyway? For me is not much important this anyway.

Indeed, it is not such important but I think it will be great to have the same behavior as a normal "in-app" menu. With the extension disabled, a menu-items in an application is called with a button released and not with a button press, the same thing for a menu-items in a contextual menu, a button, ...

**Comment by lestcape** [comment]
This error was migrated to gitlab, as the development of this extension, will no longer be in github from the recently acquisition from the Microsoft company of the github website. Please to continued following it you can subcribed in this thread:
https://gitlab.com/lestcape/Gnome-Global-AppMenu/issues/100
