### ISSUE TITLE
listing at extensions.gnome.org

### ISSUE THREAD

**Issue by navdeepio** [lestcape/Gnome-Global-AppMenu#26]
any plans?

**Comment by lestcape** [comment]
I'm against of work for any company or community or whatever that not work only for users and without receive money/donations. Gnome have his own intentions, his own patterns that i don't shared and also they sure could see this extension against his own intentions. So not, i don't want to do anything like that, but i don't care if will be the decision of other people create a package or add the extension to the gnome site.

This extension have his own API (as possible) and the things are not implemented in the same way of other gnome shell components (API). So, could be see as a problematic extensions, as actually exposed a lot of private gnome stuff and also patch a lot of removed code from gnome shell, making possible the usage of feature that was removed by gnome a time ago, like St.Tables and more things. So, this extension also give support for some gnome shell deprecate api, making possible the usage of some other old deprecate extensions.

**Comment by GNOME-IS-LIFE** [comment]
Any plans to make this beautiful piece of software a little less buggy or the likes? it hasn't seen an update in 10 days  :stuck_out_tongue:

**Comment by lestcape** [comment]
@GNOME-IS-LIFE Yes, of course yes, but i need the time to do it so.... I have not the time at this moment... To many changes in my real life, this is my hobby, not my real life, but yes... My real life it's less interesting to me but more necessary :(

**Comment by GNOME-IS-LIFE** [comment]
@lestcape  ya, i see! I just wanted to make sure whether this (amazing) project was dead or alive. thanks for the heads up, & I hope your real life gets more free and interesting :wink:

**Comment by elsieholmes** [comment]
> So not, i don't want to do anything like that, but i don't care if will be the decision of other people create a package or add the extension to the gnome site.

@lestcape, so you don't mind if some volunteer (like me) adds this extension to EGO and maintains it?

**Comment by lestcape** [comment]
@elsieholmes of course there are not any problem. Also i will help you if you need something.

**Comment by lestcape** [comment]
@elsieholmes My problem with the cinnamon spices rules it's because the rules force the thrid-party cinnamon developers to work for Mint (Mint and cinnamon are not the same things). Some thrid-party developers hosted his code in spices (thats was a mint services where thrid-party developers only hosted the code, in his name). With the new rules, they are modifying the work of the thrid-party developers in the name of the  developers instead of in his own name. Is an issue like if google will open my inbox, to answer my emails in my name, this is not ok to me. If you want to change how the extension work, make it in your name and i have not problem with it, also if you are only hosting it with my name, but without change it, there are not problem...  The usage of my name to do something that i don't aprove it's then the problem for me. if I was not who hosted the code, i don't care what you want to do with the code, is free software.

**Comment by GNOME-IS-LIFE** [comment]
damn cool 👍

**Comment by lestcape** [comment]
https://extensions.gnome.org/review/7037

**Comment by HEXcube** [comment]
Hope the extension gets approved soon! :relaxed:

**Comment by lestcape** [comment]
Was approved...

**Comment by HEXcube** [comment]
Yay! :smiley: Extension is now available at https://extensions.gnome.org/extension/1250/gnome-global-application-menu/
