### ISSUE TITLE
Alt opens File menu

### ISSUE THREAD

**Issue by bill-mavromatis** [lestcape/Gnome-Global-AppMenu#27]
I have set Alt-Shift to change my keyboard layout, but whenever I press it, the "File" menu pops. Also whenever I press Alt+(any key) the window loses focus. Alt-Tab seems to be working fine.

On second look, it looks that only Alt opens the file menu. Is this expected?

**Comment by bill-mavromatis** [comment]
Whoops, I just realised that the setting is in the extension menu! Sorry for that! 

For future reference, I would kindly suggest that the default button is not left Alt (because it's very often used) but maybe right Alt.

**Comment by lestcape** [comment]
Yes i considered you are right, but actually what i try to do is a general behaviour for handled the keyboard shortcut (something similar of how this work on cinnamon), alt it's the most complicate key (i think). So, i take it key as a reference, because as user can select any key, this will need to work also for alt.

**Comment by lestcape** [comment]
Sure, this need more work on the future, because is not working ok yet.
