### ISSUE TITLE
How do I set order priority? (conflict with Pixel Saver)

### ISSUE THREAD

**Issue by bill-mavromatis** [lestcape/Gnome-Global-AppMenu#29]
Hi @lestcape. I have already posted this issue in Pixel Saver: https://github.com/deadalnix/pixel-saver/issues/129 If you don't know it, pixel saver is an extension that merges the window icons in the top bar, when a window is maximised.

My question is how do I override the priority to put global menu on the right of the icons? Is there a config or css file? I tried to look for one but couldn't find. 

Thank you in advance!

**Comment by lestcape** [comment]
@bill-mavromatis to be honest i think this is an issue of gnome-shell and is not related with any particular extension... 

I think the best solution that it's on my hands, could be just implemented another extension to add support for move the actors inside the panel to the position that users want... A pretty slow solution as is create another extension.

I can try to play with pixel saver, but as you can see this is exactly the focus of most issues here. Users want to have the extension in different positions and display it in a different ways. I think, i can not resolved all inside the extension, but i can make the extension independent of any other actor inside the panel and then create another extension to configure the panel, like on cinnamon it's possible... Not, like this:
https://github.com/lestcape/Classic-Gnome
because this involved more than only allow move actors inside the panel, but something more particular for this case itself.

**Comment by bill-mavromatis** [comment]
I understand, thank you for the reply, I will try to check what are my options. I found this and it's useful: https://askubuntu.com/a/661015

I can do something like that:

> Open the according extension.js and change the word "right" to "left" in those two lines:
> Main.panel._addToPanelBox('dateMenu', dateMenu, -1, Main.panel._rightBox); and Main.panel._rightBox.insert_child_at_index(dateMenu.actor, -1);.

So I can manually go in extension.js and change the settings. Thanks again.

**Comment by GNOME-IS-LIFE** [comment]
@bill-mavromatis so does that manual word changing, well, change anything? Does it work? :question: :eyes:

**Comment by bill-mavromatis** [comment]
@GNOME-IS-LIFE well unfortunately, nothing I tried so far worked out. If you look into extension.js it seems to use this:

`    let activities = Main.panel.statusArea['activities'];
`
From my understanding, Global Menu takes the place of "Activities"... I tried to move it with another extension called Activities Configurator, but didn't work. Maybe it'd be easier to move pixel saver instead...

**Comment by lestcape** [comment]
@bill-mavromatis yes, this is why i tell you, i need to make the extension independent of any other (the activity is used). I can add the actor inside the panel in several ways, but of course i can not prevent all possible panel configuration. This is why i tell you the real solution will be create another extension to configure the gnome shell panel as a user preference.

**Comment by mweisshaupt1988** [comment]
This works for me: https://github.com/lestcape/Gnome-Global-AppMenu/pull/14/commits/af3bb76d8f43463540b14fea90aeb8246a41b0b0

Not perfect but the workaround is good enough for me at the moment. Looking forward to what lestcape will create :)

**Comment by bill-mavromatis** [comment]
@mweisshaupt1988 How did I miss that? 🐙 🐙 🐙 🐙  That's awesome! I think I will be using that for my script! Many thanks!

**Comment by lestcape** [comment]
The patch https://github.com/lestcape/Gnome-Global-AppMenu/commit/af3bb76d8f43463540b14fea90aeb8246a41b0b0 was merged... I need to do more things anyway...
