### ISSUE TITLE
Alt "overlayKey" conflicts with shortcuts that include Alt

### ISSUE THREAD

**Issue by Lesik** [lestcape/Gnome-Global-AppMenu#51]
Hey,

the "overlayKey", which is Alt by default, conflicts with other shortcuts that include Alt.
For example, in Firefox and Nautilus, there is `Alt + ←` to go back.

This is especially annoying, because not only does it toggle the overlayKey instead, it also means the focused application loses focus! So if you are using Nautilus, you press `Alt + ←` to go back, and then you want to continue using Nautilus, you have to use your mouse to click the application, so it regains focus.

I made pull request https://github.com/lestcape/Gnome-Global-AppMenu/pull/50 to temporarily overcome this issue (as clicking the shortcut, then pressing escape to remove it, doesn't actually remove it for me), but it would be great to fix this in the long term to not conflict with other shortcuts.

I also speak Spanish, if that's easier for you.

**Comment by lestcape** [comment]
**Short answer:**
About your pull, why you are creating a way to disable the key-binding? Is not the alt key who cause this or is all keys? If you want to resolve this problem, just easy changed the default key to other instead of disable the whole key-binding and add another option to only do that.

**Long answer:**
Ok, i know the current key-binding mechanism is really problematic. This is because in gnome shell, there are a lot of restrictions and obscurantism about this... Some key-binding are handled by mutter while others not (like the multimedia). For another hands the normal mutter key-binding, only react to a key press and not to a key-relase. In the case of alt the key-release will be handled in the global menu implementation forcing to fire a the corresponding signal, to be controlling the shell stage keyboard event. This is nothing nice an introduced a lot of problems, like you can see.

To be more complicated, in gnome shell some key-binding are hard set in the code and others can be loaded form a gsettings schema. When they are loaded from a gsettings schema, i can not find a way yet to changed it (override it), i try to find a way, but that include discover the gsettings schema definition of where they are set, to then be possible unset it. 

To be more complicated, in gnome shell was introduced a concept of keyboard grabber and a concept of key-binding priority. So, some key-binding can be transfer directly to the shell and another’s with more restriction can be intercepted and discarded when for example a popup menu is opened (a modal actor is open).  The less restrictive way is also restrictive in some context. This mean a directly action that the user introduce with a key-binding, could not be processing in some context and this is absurd. The shell can not restricted the user action, not at less without inform to the user what wrong thing is going to happen... I think in all case there are nothing wrong, just is the shell trying to prevent conflict, but at the same time this set a limit to what is possible, and then if you are not happy with it, your solution will be over-pass all this restriction with a hack of the shell code, again nothing nice, but necessary.

Finally, in this context is really annoying the hack that i introduced to be possible have a good control of the key-binding mechanisms.

**Comment by Lesik** [comment]
What if we don't keybind `<Alt>` to focus the whole menu, but instead `Alt + f` for "File", `Alt + e` for "Edit", etc.? This would also be how it's done in Gtk by default (no global menu), so people coming from no global menu would be already familiar with the keybindings.

![screenshot](https://developer.gnome.org/gnome-devel-demos/stable/media/menubar_choices.png)

Then, we could highlight the key that needs to be pressed to open the menu with an underscore:

![screenshot](http://php-gtk.eu/files/gtk-menubar-overview-componants_0.png)

**Comment by lestcape** [comment]
I don' t remember why i desist to add a thing like that in cinnamon when i try, of course this will be ok and good, probably in gnome shell will be different of cinnamon and possible. Anyway I think we need to fixed the key-binding mechanism first or it will be impossible, really this have not a good implementation...

**Comment by lestcape** [comment]
@Lesik https://github.com/lestcape/Gnome-Global-AppMenu/commit/d7a950c2247e803ede2d8b6f1dada5640d758725
