### ISSUE TITLE
drag top bar

### ISSUE THREAD

**Issue by Richie-8DK** [lestcape/Gnome-Global-AppMenu#54]
# Pixel Saver support
Pixel Saver is an [GNOME extension](https://extensions.gnome.org/extension/723/pixel-saver/)[(Github)](https://github.com/deadalnix/pixel-saver), that hides the titlebar of maximazed windows without a headerbar, like unity. 
If a window is maximized you can drag the top bar, insteaad of the titlebar of the window. This is a standart GNOME feature. But if I hover over the Global Appmenu, I can't drag the window on the top bar. First I have to click on the application window again.
Also if hover over the Global Appmenu, it highlights and stays highlighted. Untill I click somewhere else.

###### Look
Also it would be nice to be able to disable the fade of the application name.

**Comment by lestcape** [comment]
1- I don't understand what you want to drag  and where you can drop it. 
2- Yes, this is an style problem that i need to fix. Low priority to me, there are worse problems.
3- It's erosible disable the fade of the application name in the settings.

**Comment by lestcape** [comment]
Ohh yes. I understand the point one now... Yes the menu gain the focus and then you can not drag the top bar. The menu is designed to work along of the gnome shell panel menu. So, the menu launcher is not the panel (is the extension actor) and the focus can not be placed in the panel then. So, this will not work for that. 

I don't know if i can do something on this problem... I also don't like handled the focus in a different way of gnome shell (as is currently), but also is impossible to have a menu like this using the standard popup menu system of gnome. Will be really hard redefine how my popup menu api is working, because all is related with what menu actor have the focus and this is exactly the problem.

**Comment by lestcape** [comment]
You can confirmed that the problem is resolved...
