### ISSUE TITLE
Root apps don't have menu

### ISSUE THREAD

**Issue by HEXcube** [lestcape/Gnome-Global-AppMenu#64]
Apps running as root don't show menus, neither in Global Menu section or in conventional menubar. In Unity 7_ too root apps wouldn't show global menus, but then regular menubars'd show up. See examples of the issue:

**Synaptic as Root**:

![synaptic root](https://user-images.githubusercontent.com/3755396/30523344-74bb616e-9bfd-11e7-96be-536daec14661.png)

**Synaptic without Root**:

![synaptic noroot](https://user-images.githubusercontent.com/3755396/30523353-90227064-9bfd-11e7-8350-540eed7d885f.png)

**GNOME Text Editor with and without Root**:

![gnome text root](https://user-images.githubusercontent.com/3755396/30523386-1f9ef9ec-9bfe-11e7-9982-f8ed3ad00c75.png)
![gnome text noroot](https://user-images.githubusercontent.com/3755396/30523389-26fe93aa-9bfe-11e7-8509-2dfc996bfeb7.png)

**GNOME Files with and without Root**:

![gnome files root](https://user-images.githubusercontent.com/3755396/30523404-5c4d303e-9bfe-11e7-8a51-e7385f17cc39.png)
![gnome files noroot](https://user-images.githubusercontent.com/3755396/30523405-607b3426-9bfe-11e7-96af-e8d69ab23337.png)

Note that GNOME Files shows a blank AppMenu in Global Menu, but a proper AppMenu in headerbar.

**Comment by lestcape** [comment]
Hi @HEXcube, the extensions are not really installable with root privileges if you don't make a package to it (like this extension), then i have not a way to define a pam module for security or something to be possible detect scalability of privileges. In that context and how I really can not "pre-hack" the .desktop files because i'm not a distro, the only solution that i found was set that form settings, with the inconvenient that will be set statically, because i have not a daemon or something running constantly to evaluate thing like that and i can not really add one in this context.

As the procedure is statically, is resulting in a change of your environment that you will need to care about when you uninstall the extension. As this force the environment variables for the global menu, you also could lost flexibility in other options of the global menu.

For all that reasons this option is set as experimental for the very begin and is the first option of the global menu settings.

**Comment by lestcape** [comment]
![captura de pantalla de 2017-09-18 18-41-44](https://user-images.githubusercontent.com/1389572/30569621-7d35c60a-9ca1-11e7-97cf-e74715456569.png)

**Comment by lestcape** [comment]
If you want to uninstall the extension, set this settings option to off, then uninstall the extension.

**Comment by HEXcube** [comment]
So, if I install to **/usr/share/gnome-shell/extensions/** instead of the usual _"~/.local/share/gnome-shell/extensions/"_ will it be step closer? It's where Ubuntu's new Dock and Indicator extensions come preinstalled.

**Comment by lestcape** [comment]
No, to be really solved it need more than only a gnome shell extension code. It really can not be resolved with only gjs code. So, need to be more than only an extension, need to be a real integrate application with also the extension code, but not only the extension code. Otherwise a direct communication with the pam service of the gnome session. I really don't give you a well idea of all that is really needed, because is something that i don't want to do it's out of the scope of the extension itself and there are workarounds like you can see.
