### ISSUE TITLE
After passing the mouse, the application loses its focus and does not recover the focus

### ISSUE THREAD

**Issue by ErickTucto** [lestcape/Gnome-Global-AppMenu#68]
I pass mouse and applications(sublime text, firefox, chrome, etc) loses the focus. After I remove the mouse from above the menu and the application does not recover the focus

Example with Firefox:
![imagen](https://user-images.githubusercontent.com/22831024/33093610-683220c6-cecb-11e7-95cc-a7d0beac2d1c.png)

PD: I speak Spanish so the menu is in that language

**Comment by lestcape** [comment]
Yes, thanks. I know thats happens. Cinnamon and Gnome handled the focus in a different way and the global menu was designed for cinnamon, not for Gnome. I have a large update that fix this, but not in all cases. The remaining case i when you hit the a key binding that it's a modifier (Alt key for example), because gnome can not handled the key release event and i need to set the focus on the stage (to the clutter components to capture by my self the key release).

I don't update the extension with that change because i have troves with the keyboard navigation, and because i don't know how resolve property the orca screen reader bug. Orca can read the Akt element that actually have the focus and i simulate a focus move in several places without really move the focus. All this is related with the same, the focus and i want to find a good way to resolved all this at once. 

I also speak Spanish, as is my primary language. What i don't speak is English, so...

Thanks for take the time to report it.

**Comment by lestcape** [comment]
Hi. You can tell me if after this https://github.com/lestcape/Gnome-Global-AppMenu/commit/ba661b8cd982b01adf7493ab1282610d494f550a the problem is solved...

**Comment by ErickTucto** [comment]
Thank. The new change is work correcty. Your extension is the best.
