### ISSUE TITLE
just a request for change 

### ISSUE THREAD

**Issue by Mamad026** [lestcape/Gnome-Global-AppMenu#69]
Hi.
We haven't any Global menu for Gnome so it will be very good if you provide one. I know this extension that you provided do what I say but It will be better if you remove other useless features and keep global menu or provide a new a extension that it provide just a global menu in panel just like other desktop environments like KDE Plasma, etc. 
Thanks.

**Comment by lestcape** [comment]
Sorry, what? Can you list this useful features?

Don't take it personal, because probably you have right and there are things that are not useful. 

Actually i think the features are for something:

1- A user request.
2- A hack, that can or not be active as a decision of the users (and this required to be an option, because IS A HACK).
3- Features that required a change in the user profile (need to be a decision of the user active it or not, because it modify the USER profile).
4- Different behaviours that are supported by the API and in my opinion hidden it to the user is try the user as an idiot  without the power to configured the things in the way it want.
5- Features that are not fully implemented because of a bug or something else. Remember this extension is in **BETA**.

Also this extension is discontinued as you can read here: https://github.com/lestcape/Gnome-Global-AppMenu/issues/63 so, maybe all this is for nothing.

**In my personal opinion**: I dislike the minimalist design of gnome and then i'm gains to remove features and provide something that can not be accommodate to more types of users. If a user don't want to have many options, i can not help then, because in my opinion, this last type of users only think in him self and i don't make software for money and less for the satisfaction of individual users or personal criterials, like occurs and you mention in "other desktop environments like KDE Plasma, etc." I'm not a company, i don't follow any convention of a company and i don't make software of this style. 

For other point of view, yes probably like you say: "will be better if you remove other useless features" and also probably will be better if all people will like to have the same things to no worried about configurations, but we are humans and we have preferences.

So, probably i can not satisfy you request, as the extension is free software, you can try to convince other people that think in that your own way to do what you want.

Regards.

**Comment by Mamad026** [comment]
Yes, it seems like a personal request but I won't ask it and OK!
Thanks for the answer

**Comment by lestcape** [comment]
I think is just a different and opposite conception of how we perceived that things need to be. I don't say i have right, just i say that your request is go to a different direction of what i want to do and i explain you why. You can agree with this or not and that not mean you are wrong just it is not my direction.

Take this on account, is more easy remove one feature that add one. In the worse case you can think there are not options, there are not a settings and use the extension as it's by default. I don't see how can interfere with you vision something that you don't want to use, if you just don't used it really. For the another hand not have the options will of course affected the people that want to have a different things like me.

**Comment by Mamad026** [comment]
Good idea 👍 
Thanks.
