### ISSUE TITLE
Feature suggestion: force-quit

### ISSUE THREAD

**Issue by escallic** [lestcape/Gnome-Global-AppMenu#70]
I like to have the xkill icon handy when specifying (and force-quitting) unresponsive apps. But if the app draws over the sole interface, then it is already the active specimen. It would be more intuitive to think of force-quit as residing _inside_ its context, thus inside the Global menu, therefore eliminating the connotation of a separate app icon for force-quitting it.

TL;DR
I suggest Gnome-Global allows a developer option to show a force-quit entry for the active app.

**Comment by lestcape** [comment]
I think this is an interesting thing to have, i will like to have it too. Just i 'm worried about the support of this outside X11. Whatever, this will have to wait to see what will be the decision of the ubuntu team about Wayland as a default for 18.04 and the support that the global menu could have or not in Wayland session.

For another hand i think that also need to have less priority than support the windows buttons inside the global menu. One of the things i will like to add is the ability for parse the Gtk style and build the windows buttons on fly.

As you can see, it will take a long here, so i propose you to also report it to the window buttons extension (https://github.com/danielkza/Gnome-Shell-Window-Buttons-Extension). I think it's more according right now, if this feature will be added as part of this extension, as actually is who really have an implementation of the window buttons. So, add another as an option probably is not so hard in this extension.

I don't like to add the code of this extension, because they don't use the current gtk style. What they really have instead are predefine buttons.

**Comment by lestcape** [comment]
Added some usefull ideas to implement the windows buttons.

The Gtk.Style of windows buttons is:
```
headerbar.titlebar button.titlebutton.close
headerbar.titlebar button.titlebutton.maximize
headerbar.titlebar button.titlebutton.minimize
```

So we need something like this:

```
let pathHeaderBar = new Gtk.WidgetPath();
pathHeaderBar.append_type(Gtk.HeaderBar);

let pathButton = new Gtk.WidgetPath();
pathButton.set_parent(pathHeaderBar);

let contextHeaderBar = new Gtk.StyleContext();
contextHeaderBar.set_path(pathHeaderBar); //How???????????????? adding another append_type
contextHeaderBar.add_class('titlebar');

let contextButton = new Gtk.StyleContext();
contextButton.set_path(pathHeaderBar);
contextButton.add_class('titlebutton');
contextButton.add_class('close');
```
The Gtk.WidgetPath:
https://people.gnome.org/~gcampagna/docs/Gtk-3.0/Gtk.WidgetPath.html

The Gtk.StyleContext:
https://people.gnome.org/~gcampagna/docs/Gtk-3.0/Gtk.StyleContext.html

Then we will need to see the Firefox csd implementation, for more useful ideas:
https://reviewboard.mozilla.org/r/62486/diff/1#index_header

Specially:
```
moz_gtk_button_paint(cairo_t *cr, GdkRectangle* rect,
                     GtkWidgetState* state,
                     GtkReliefStyle relief, GtkWidget* widget,
                     GtkTextDirection direction)
{
    GtkStateFlags state_flags = GetStateFlagsFromGtkWidgetState(state);
    GtkStyleContext* style = gtk_widget_get_style_context(widget);    
    gint x = rect->x, y=rect->y, width=rect->width, height=rect->height;

    gtk_widget_set_direction(widget, direction);
 
    gtk_style_context_save(style);
    gtk_style_context_set_state(style, state_flags);

    if (state->isDefault && relief == GTK_RELIEF_NORMAL) {
        // handle default borders both outside and inside the button
        gint default_top, default_left, default_bottom, default_right;
        moz_gtk_button_get_default_overflow(&default_top, &default_left,
                                            &default_bottom, &default_right);
        x -= default_left;
        y -= default_top;
        width += default_left + default_right;
        height += default_top + default_bottom;
        gtk_render_background(style, cr, x, y, width, height);
        gtk_render_frame(style, cr, x, y, width, height);
        moz_gtk_button_get_default_border(&default_top, &default_left,
                                          &default_bottom, &default_right);
        x += default_left;
        y += default_top;
        width -= (default_left + default_right);
        height -= (default_top + default_bottom);
    } else if (relief != GTK_RELIEF_NONE || state->depressed ||
        (state_flags & GTK_STATE_FLAG_PRELIGHT)) {
        // the following line can trigger an assertion (Crux theme)
        //   file ../../gdk/gdkwindow.c: line 1846 (gdk_window_clear_area):
        //   assertion `GDK_IS_WINDOW (window)' failed
        gtk_render_background(style, cr, x, y, width, height);
        gtk_render_frame(style, cr, x, y, width, height);
    }

    if (state->focused) {
        GtkBorder border;
        gtk_style_context_get_border(style, state_flags, &border);
        x += border.left;
        y += border.top;
        width -= (border.left + border.right);
        height -= (border.top + border.bottom);
        gtk_render_focus(style, cr, x, y, width, height);
    }
    gtk_style_context_restore(style);
    return MOZ_GTK_SUCCESS;
}
```

**Comment by lestcape** [comment]
This error was migrated to gitlab, as the development of this extension, will no longer be in github from the recently acquisition from the Microsoft company of the github website. Please to continued following it you can subscribed in this thread:
https://gitlab.com/lestcape/Gnome-Global-AppMenu/issues/70
