### ISSUE TITLE
Extension stealing focus from new windows

### ISSUE THREAD

**Issue by LKGames** [lestcape/Gnome-Global-AppMenu#71]
Steps to reproduce:
1: Open an application from anywhere other than the overlay (such as Settings from the menu in the top right) with this extension enabled
2: Notice that the focus is moved from the window to the application title. (The window becomes inactive, and an underline appears below the application icon/title).

The version from the official Gnome extensions website does not have this issue, but it causes gnome-shell to crash frequently.

Somewhat related: Does Gnome provide an API for creating "native" menus (like the clock and their default AppMenu, for example)? It would be nice to have all menus work consistently, and it would probably solve this issue as well, since their menus don't take focus when activated.

**Comment by lestcape** [comment]
The problem with the focus is known: https://github.com/lestcape/Gnome-Global-AppMenu/issues/68

The Gnome Menu API, is a toy for me, because do not support to open more than one menu at the same time. The Menu API really is not the problem. The problem is used a menu API that was conciebed from Cinnamon in Gnome without changed it.

Of course here we need a fix. I don't reproduce this specific issue yet, but i know the focus are not handled consistently with other Gnome components.

Thanks.

**Comment by LKGames** [comment]
Hi, I just noticed the 'fixFocus' branch. I wanted to let you know that I tried it, and it resolves this problem completely. Thanks!

**Comment by lestcape** [comment]
Yes, but that is an incomplete branch. That is why is a branch and not the master. You have not support for keyboard navigation in this branch yet, as i will redefine all to work like on gnome shell.

I will request your help when i finished this branch, to see if all that you request really was fixed. I have the time now (some days at less), so i will fixed this problem as it's really annoying.
