### ISSUE TITLE
Menu in title bar?

### ISSUE THREAD

**Issue by yannnou** [lestcape/Gnome-Global-AppMenu#76]
Hello,
Great extension! Still using X because of other limitations of Wayland (like running synaptic).

Moving away from Unity what I really miss is the menus in the title bar of the application, rather than in the top bar (I use focus-follows-mouse...). As your extension is the only one I found to come close to the Unity feel, could this be an option? I admit I have no clue how much work it may represent...

Thanks
Yann

**Comment by rilian-la-te** [comment]
AFAIK, it can be registered as right-click menu, because gnome-shell draws it.

**Comment by lestcape** [comment]
To be honest, i don't know what occurs on unity to be possible set the menu in that way. One thing is clear to me, i can not make it in a clutter extension like it's, because is a different toolkit of the application itself. Probably, i can do something in Gtk (only), if i embedded the menu inside a gtk widget and then set the widget in the title bar, but really that will be like a Frankenstein, as we will merged different toolkits. Another possibility is registered the menu as right-click menu, like the @rilian-la-te comment, but it's not the same, because the menu will not be display embedded with the title bar at all.

So, really this is not something related with the shell itself and is more related with the scope of the toolkits.

It's not really interesting to me hack the toolkits, because it's not a shell related things and will be a lot of code that we need to keep update.

If someone will create a package to move the menu to the title bar, i can modify the extension to follow that order and do not export the menu in this case or something like that, but really there nothing right that i can do in gjs to satisfy your request.

**Comment by rilian-la-te** [comment]
Unity IS a WM, so it just take menu from Registrar and unity-gtk-module and move it to titlebar. But for gnome-shell we need to hack mutter to do it AFAIK.

**Comment by lestcape** [comment]
@rilian-la-te well, it can not be a gtk-module and a qt-module?

I thing it will be possible without modify mutter, just probably not for any app and only for gtk and qt app.

**Comment by rilian-la-te** [comment]
How, if mutter is thing than draws a windeco?  (we can write gtk module and use GTK_CSD instead, but for me it is a weird hack)

**Comment by lestcape** [comment]
@rilian-la-te yes, we are agree now, it will be a crude hack. But i think also that it's currently a crude hack in unity. Just probably the canonical team have the time and the resources to do that, but we can not lost our time just to hacking all linux toolkit, at less not me.

**Comment by rilian-la-te** [comment]
In Unity it is less hacky, because it uses its own source code, but not gnome 's.

**Comment by rilian-la-te** [comment]
Because in Unity it draws windeco itself.

**Comment by lestcape** [comment]
Ok, but what they do on unity it's not an option to us. The option to us is outside the desktop scope, is make it in a module, so have not sense to worried about what we can not modify. If we modify the WM, we will have another different desktop. This is not interesting to me at all.

**Comment by lestcape** [comment]
Ohh well that other history then, i really don't want a WM. That means to me i will have a new distro and a lot of work to do... This is a thing i can do for money, not as a hobby.

**Comment by rilian-la-te** [comment]
Why a new distro?
WM is needed for Wayland because we need compositor support for Global Menu (you already use Mutter for this role)

**Comment by lestcape** [comment]
Because in the currently gnome conception of the desktop, the window manager it's about 80% of the desktop right now. All is working inside the windows manager as a plugging and other things are just for settings things to be use inside the WM.

If you have a new window manager, you have a new conception about of the 80% of the desktop. Like is in my opinion stupid buy a new processor a not buy a new board, is also stupid understand and create a new compositor, just to play with it without taking any monetary benefit.

**Comment by lestcape** [comment]
Closing this as will not be implemented.
