### ISSUE TITLE
Memory leak when opening menus

### ISSUE THREAD

**Issue by Userwithaname** [lestcape/Gnome-Global-AppMenu#78]
The extension allocates about 0.8 MB of memory to `gnome-shell` every time a menu is opened. You can observe this by opening the gnome-system-monitor and the terminal, opening one of the terminal's menus, then moving the cursor over the other menus.

PS: Awesome extension, thanks for all the work you put into it

**Comment by lestcape** [comment]
@Userwithaname ok and...? What is a bug it's not that the extension allocate memory. The bug could be that memory is never released. Gnome shell have a garbage collector and the garbage collector is execute when hi want not when we think need to be executed. 

So, the extension need memory and CPU to work and this is not a bug at all.

Then, what is your point?

**Comment by lestcape** [comment]
Just make the same procedure with the activity button, without have the global menu extension enabled and then see if you notice the same or not. A shell memory leak? Wherever there are image or a big code is execute that will occurs in gnome shell.

If you can proved some how that the memory allocate by the extension never is released, probably there are a bug inside the extension.

To be honest, it's probably there are a memory leak, because will be really a rare if not, but your comment dosen't not tell me anything about a memory leak or about where could be that leak. So, there are nothing i can do to trying to find it different of what i always try to do.

What could help to find a bug (**for example**)?

1- Is systematic (always occurs or in some condition only).
2- Is more less the same quantity, not matter the number of items or images in a popup menu.
3- Is occurring for Gtk applications but not for Qt applications.
....

And more condition that you can notice to isolate the problem and find where the leak could be.

**Comment by Userwithaname** [comment]
I must apologize for opening this issue before doing more research. The default menu has this problem as well, as do many other parts of the shell, so it might just be how Gnome works. I guess it's an issue with Gnome itself, then.

**Comment by lestcape** [comment]
Not worried and thanks for report what you considered a bug. For me a memory leak is the most difficult problem to be detected and fixed in the shell. Never it's pretty clear where it's and in what conditions occurs. So, like it's pretty hard, i prefer do not try, unless I have an info that give me a chance to isolate a memory leak, to then be possible find the cause.

Anyway it's for me much more easy detect a leak if we see the code than if we try to observe the system monitor in gnome shell. There are more powered tools to detect leak, but it's also pretty hard to used it.

**Comment by lestcape** [comment]
I made some time ago an applet for cinnamon to detect a memory leak and for force the garbage collector to execute a clean: https://github.com/lestcape/Garbage-Collector, probably will be a good idea port it to gnome shell. I know a memory leak could be really annoying.

Also In the recently gjs code, the garbage collector is set to be much more aggressive. So, sure is more easy notice a memory leak than in the version of gjs i currently have.
