### ISSUE TITLE
Make menu show when panel is hovered

### ISSUE THREAD

**Issue by chrisnharvey** [lestcape/Gnome-Global-AppMenu#80]
Hi there,

Love this extension, thanks for all your hard work.

I'm trying to add a feature where the main menu will only display in the panel when the mouse enters the panel, and hides when the house leaves the panel, similar to how Unity works.

I want the menu to stay visible if a submenu is open, but currently all the menus just close when the mouse leaves the panel.

![demo](https://user-images.githubusercontent.com/619298/36345393-46e69212-1421-11e8-8b8c-f4f9b5b4c7aa.gif)

I have connected a function to the panel's "leave-event", but the _activeMenuItem on this.menu is null. It seems to be only set to null when accessing it from the leave event. I was going to check _activeMenuItem from the leave event, but it is inaccessible.

Any ideas on how I can solve this?

**Comment by lestcape** [comment]
Well yes, you are trying to modify the most complicate shell stuff. This is all related with the focus and behaviour in general. It's really complicate, because the items only have the focus when the pop-up menu is opened, while is not opened it can not gain the focus, because that mean steals the focus from the window. You can read a lot of issue about the focus here.

I think you can not connect anything externally, you need to enter inside the API and modify it according of what you want and will be also really complicate.

**Comment by lestcape** [comment]
This is probably the thing that create bugs to you:
https://github.com/lestcape/Gnome-Global-AppMenu/blob/master/gnomeGlobalAppMenu%40lestcape/configurableMenus.js#L8170-L8174

It's an ugly code, but is the way of how i can handled it.

**Comment by lestcape** [comment]
If you want, i can try to make the things a little more easy to you... But i can not promise anything, because also will be difficult to me, but like you see is also a thing i want to fix.
https://github.com/lestcape/Gnome-Global-AppMenu/blob/master/gnomeGlobalAppMenu%40lestcape/configurableMenus.js#L8168

**Comment by chrisnharvey** [comment]
Making it easier would be ideal. Any help would be greatly appreciated.

What I was thinking might be a way around it, is to disconnect the panel "leave-event" when a submenu is opened, then reconnect it when the submenu is closed. So the event would only be fired when there is no submenu open. Could this work?

**Comment by lestcape** [comment]
https://github.com/lestcape/Gnome-Global-AppMenu/blob/master/gnomeGlobalAppMenu%40lestcape/configurableMenus.js#L8050-L8051

If focus on hover it's set it will gain the focus on hovered. If something active it it will also gain the focus.

**Comment by lestcape** [comment]
This error was migrated to gitlab, as the development of this extension, will no longer be in github from the recently acquisition from the Microsoft company of the github website. Please to continued following it you can subscribed in this thread:
https://gitlab.com/lestcape/Gnome-Global-AppMenu/issues/80
