### ISSUE TITLE
Cannot display settings window on GNOME 3.28, Ubuntu 18.04

### ISSUE THREAD

**Issue by njlyf2011** [lestcape/Gnome-Global-AppMenu#81]
It could be a bug...

**Comment by vali20** [comment]
No, it is not, just a missing dependency. Same as for Activities Configurator. Install the following:
``sudo apt install gir1.2-clutter-1.0 gir1.2-clutter-gst-3.0 gir1.2-gtkclutter-1.0

**Comment by lestcape** [comment]
Probably is enough install gnome-tweak-tool??? At less, i don't suffer for that missing dependencies.

Anyway, we will change some important dependencies... We will leave to use unity-gtk-module in favour of appmenu-gtk-module (https://launchpad.net/ubuntu/+source/appmenu-gtk-module) as soon as possible.

**Comment by vali20** [comment]
I had gnome-tweak-tool installed without the above and it did not work like that. Then, I modified the settings from the config file manually and forgot about the UI. Then, i moved on to installing Activities Configurator and with that I found out that its settings UI needs those above dependencies in order to work. Then, I just randomly opened the global menu bar's settings and found out it works, and uninstalled the modules and saw that it did not work anymore. That's how I came to the conclusion it may work with above workaround.

**Comment by njlyf2011** [comment]
OK...
Thanks!

**Comment by lestcape** [comment]
@jbicha Where this can be reported?

**Comment by HEXcube** [comment]
I thought it was changes in the new GNOME Shell that broke it. Thanks to @vali20's solution, the extension settings window works fine now. :smile:

**Comment by lestcape** [comment]
Yes, but Gnome-shell nor need that dependencies. Are the extensions with a javascript-gtk settings who need that dependencies. Like an extension can not add dependencies in any way, i think this is a task that can be resolved by gnome-tweak-tool. This is why i alert @jbicha who is the developer of the gnome-tweak-tool, to see if he can do something about it.

**Comment by lestcape** [comment]
This error was migrated to gitlab, as the development of this extension, will no longer be in github from the recently acquisition from the Microsoft company of the github website. Please to continued following it you can subscribed in this thread:
https://gitlab.com/lestcape/Gnome-Global-AppMenu/issues/81
