### ISSUE TITLE
Windows Title too short and some idea.

### ISSUE THREAD

**Issue by xenlism** [lestcape/Gnome-Global-AppMenu#92]
![hud](https://user-images.githubusercontent.com/13846221/39740017-f76d760c-52bd-11e8-99f7-0ef05abf35db.png) app tile too short.

I have idea for you.
1. Window Tile full length and show menu on mouseover.
![hudmokup](https://user-images.githubusercontent.com/13846221/39740068-2db83f9e-52be-11e8-8093-b94a885a0145.png)

**Comment by lestcape** [comment]
> Window Tile full length

You can change "the windows title" size in the settings, but it have a limit always, because some developers could set a really big title, affecting how the menu is displayed. Really, what is displayed is the app title. Waverer a window title or an application title, it could have a long size and i don't like to break all things, just because someone set a really big title.

Also read related issues here and inside the cinnamon global menu repository: https://github.com/lestcape/Global-AppMenu/issues?q=is%3Aissue+is%3Aclosed

So, Won't be fixed.

> Show menu on mouseover

Is waiting to be implemented: https://github.com/lestcape/Gnome-Global-AppMenu/issues/80

**Comment by lestcape** [comment]
Now i remember that if you set the the application name size to the value: **0** in the settings, it will show all the name not matter what.

**Comment by xenlism** [comment]
Thank you.

**Comment by lestcape** [comment]
Well i also added an option to display the window title instead of the application name and i'm working in the hover functionality. This is why i remember that possibility...

Also I have the idea of merge the windows buttons as an option, please see: https://github.com/lestcape/metacity-buttons it's a real Gtk3 windows buttons that are generate base on the current used gtk3 theme. Is not like pixels saver, with have just some customs themes only. So it will work for your preferred Gtk3 theme, without do nothing more.

**Comment by xenlism** [comment]
Good job.
