### ISSUE TITLE
It's not working On Idea 2018.1

### ISSUE THREAD

**Issue by spectrejie** [lestcape/Gnome-Global-AppMenu#93]
![idea](https://user-images.githubusercontent.com/10397992/39954428-d5e20d4a-55f1-11e8-9ff2-bc5a7d7b17d7.png)

It's not working On Idea 2018.1,most of the other applications are working fine.
OS:Ubuntu 18.04
Idea:2018.1

**Comment by lestcape** [comment]
Thanks for reporting it, but:

1- Do you install the jayatana package?
2- Do you active the support **EXPERIMENTAL**, for java applications in the settings?
3- Do you test if is working for other java applications?
4- Do you read other related issues here?

And also:

5-  What do you mean with "It's not working"...

![captura de pantalla de 2018-05-12 02-11-58](https://user-images.githubusercontent.com/1389572/39954756-e8cd7402-5589-11e8-8b9d-f7e36f88a60a.png)

**Comment by spectrejie** [comment]
Thank you for your reply.
"It's not working" means idea's menu doesn't work as the global menu.
I'v done the actions below:
1.sudo apt install jayatana
2.Enable the support for Jayatana in gnome teaks
3.add "-javaagent:/usr/share/java/jayatanaag.jar" into idea's vm option,then idea‘s startup will stop halfway

**Comment by lestcape** [comment]
Well, this a better report and something i can understand... I'm no a magician, so, if you don' t provide information this then not useful.

- Remove the step 3, this is what is doing the global menu settings along with other stuff more.  
- idea is not a gtk application, so it don' t need the appmenu-gtk-module, and there are not problem if it fail to load it, because what it need to load is the jayatana package and not the appmenu-gtk-module.
- I don' t know what you do, but like you see in the picture is working in my computer.
- Do you test if other java applications are working in first place? 
- What java you are using the open source or the oracle? Try to install the oracle if not.
- Whatever it is happens, apparently is not something that i can resolve, because like i say it's working.

**Comment by spectrejie** [comment]
Thank you,I've removed the step 3,but the idea's menu still doesn't work as the global menu.
And I've test the mysql workbench,it shows the same.
![2018-05-14 18-07-27](https://user-images.githubusercontent.com/10397992/39991596-a6b0fd62-57a2-11e8-86b4-73a7836b3076.png)
My java version is oracle java 1.8.0_172
![2018-05-14 18-15-35](https://user-images.githubusercontent.com/10397992/39991680-e313b2ae-57a2-11e8-8cee-b33657511b07.png)
And my setting in the tweaks shows as below:
![2018-05-14 18-16-36](https://user-images.githubusercontent.com/10397992/39991743-15b854a8-57a3-11e8-89bd-f30c6776ac0a.png)

**Comment by lestcape** [comment]
You are in the X11 session right?

lestcape@Home-lestcape:~$ java -version
Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)
lestcape@Home-lestcape:~$ gnome-shell --version
GNOME Shell 3.28.1

There are three possibilities in my opinion:
 1- Some configuration that you have.
 2- The java version.
 3- The difference in hardware that make this unusable in your case.

For those, i can just resolve the point 3:

1- Please after idea is loaded restart the shell and see if the menu is displayed.

2- In this line:
https://github.com/lestcape/Gnome-Global-AppMenu/blob/master/gnomeGlobalAppMenu%40lestcape/indicatorAppMenuWatcher.js#L771

`Mainloop.timeout_add(200, Lang.bind(this, function() {`

Change the 200 for 500 or 1000 save and restart the shell and try again.

Let me know if some of this options resolve the problem.

**Comment by lestcape** [comment]
You have the last version of the extension right? If not download it from here: https://github.com/lestcape/Gnome-Global-AppMenu/archive/master.zip

**Comment by spectrejie** [comment]
Problem solved.
Firstly ,remove  gir1.2-clutter-gst-3.0 gir1.2-gtkclutter-1.0(I once executed the command "sudo apt install gir1.2-clutter-1.0 gir1.2-clutter-gst-3.0 gir1.2-gtkclutter-1.0" according to"https://github.com/lestcape/Gnome-Global-AppMenu/issues/81" when the settings not shown)
Then,restart ,and reopen the settings.
Then the most important,**Do Not Open The Applications By Jetbrains ToolBox**,Finally the Jetbrains apps will work OK!

![2018-05-15 18-42-19](https://user-images.githubusercontent.com/10397992/40052249-0aafdc8e-5870-11e8-8778-bd822a1e97cf.png)

**Comment by lestcape** [comment]
The only way is fixing it in the side of the developer of this this applications. Is not just the Intellij idea... All his products have the same thing.

**Comment by rilian-la-te** [comment]
To cancel a checkboxes, we should do a 2 things:
1. Catch if window is JetBrains
2. Ignore checkboxes mostly/

**Comment by lestcape** [comment]
Is just not intellij ideas only... Are all applications JetBrains applications. I'm not agree with you about make specific patches...

Probably, will be good a path in jayatana to check if the checkbox is visible and send the component as a normal item if the checkbox is not visible. I think the checkbox is not visible, because in the window menu of intellij idea is not showing.

**Comment by rilian-la-te** [comment]
No, Jayatana checks a type of MenuItem, and all JetBrains menu items given to us as JCheckBoxMenuItem (according to https://github.com/JetBrains/intellij-community/blob/86b30355c16679ea587621d626c9e90b9a2cc7c6/platform/platform-impl/src/com/intellij/ui/plaf/gtk/GtkMenuItemUI.java).

And Jayatana already have a patch for NetBeans, so small patch for JetBrains will not hurt. About rendering in checked - I do not like it, because MenuModels does not like changing menu item type, it will require a redraw of all menu item(

**Comment by lestcape** [comment]
No, i don't say rendering in checked, ofcourse this will be an abuse of update. I say rendering when the JCheckBoxMenuItem is visible. They are creating a hidden JCheckBoxMenuItem https://github.com/JetBrains/intellij-community/blob/86b30355c16679ea587621d626c9e90b9a2cc7c6/platform/platform-impl/src/com/intellij/ui/plaf/gtk/GtkMenuItemUI.java#L43

So, check if the JCheckBoxMenuItem is hidden.

**Comment by rilian-la-te** [comment]
But then we lose all menu, I assume.

**Comment by rilian-la-te** [comment]
And "hidden" does not mean invisible here. It is here for unparented AFAIK.

**Comment by rilian-la-te** [comment]
Can you check Idea with Nimbus PLAF enforced?

**Comment by lestcape** [comment]
> But then we lose all menu, I assume.

Not at all... If the checkbox is visible it will be rendered like a checkbox. If is not visible it will be render as a normal item, so it will always be rendered.

And "hidden" does not mean invisible here. It is here for unparented AFAIK.

I think probably i'm wrong or you are wrong underestimating how it work:

![exp](https://user-images.githubusercontent.com/1389572/40067336-944babd4-582b-11e8-8478-41e0d9de6ea5.png)

**Comment by lestcape** [comment]
> Can you check Idea with Nimbus PLAF enforced?

Not.

**Comment by lestcape** [comment]
@trespasserw Can you help us here?

**Comment by lestcape** [comment]
Ok, i read what is Nimbus PLAF enforced. But is supposed that it's what i'm using currently, because i'm in the gtk platform.

```
public static boolean isUnderGTKLookAndFeel() {
        return UIManager.getLookAndFeel().getName().contains("GTK");
}
```

**Comment by lestcape** [comment]
Just i want to know how differentiate a real checkbox items for the fake checkbox items they have, without to check for the checkbox visibility. If there are not way, you will eat all real checkbox.

**Comment by trespasserw** [comment]
It's true that all menu items in IntelliJ-based IDEs extend `JCheckBoxMenuItem` (I afraid we can't do anything about it). But it doesn't mean there should be a real checkbox painted beside them.

That's how it should look:
![screenshot from 2018-05-16 14-10-06](https://user-images.githubusercontent.com/594866/40116882-67dfa5ce-5915-11e8-84a0-06db6cdf862c.png)

**Comment by rilian-la-te** [comment]
I know. But how we should determine whether item is a real checkbox or fake checkbox?

**Comment by trespasserw** [comment]
I mean, is there such thing as “real checkbox” in menu items? Aren’t all such checkboxes “fake”, used only to add a binary state of an item?

**Comment by rilian-la-te** [comment]
Yes, it is. It is a real checkbox in DBusMenu, and a fake checkbox too (if it done by icon)

**Comment by lestcape** [comment]
@trespasserw 

In java there are not such thing like a DBusMenu, but some one made a java plugin called jayatana. If this plugin is enable in the context where we launch a java application as a (JAVA_TOOL_OPTIONS), the plugin is loaded with the java application and it can parse the java swing menu structure of the java application and construct a Dbus menu interface with the representation of all items inside the specific  windows menu, with his basic properties, children and more things.

How in IntelliJ, the menu items are all of the type JCheckBoxMenuItem, the jayatana tools report over Dbus that all menus are JCheckBoxMenuItem. Then whoever client of this Dbus service that reads this, is going to assume that this menu item is a checkbox and this is what will be painted.

But really they are 'fakes' JCheckBoxMenuItem in some cases(but we supposed not alls). We need to distiguish when they are really JCheckBoxMenuItem, and when they are of the type JCheckBoxMenuItem, but are not representing as JCheckBoxMenuItem. This is to then act in concordance and report over Dbus the real type (visible type) of this JMenuItems, instead of just report all as JCheckBoxMenuItem. 

So, the question es how we can detect when a JCheckBoxMenuItem is acting as a real JCheckBoxMenuItem and when is just acting as a 'fake' JCheckBoxMenuItem, but it really is a simple JMenuItem, to then be possible inform over Dbus about the efective type of this JMenuItem and not about his 'fake' type. As we really don't care inform internal desition, but instead we want to inform efective types and visibles by the user, like is displayed in your picture.

**Comment by rilian-la-te** [comment]
@lestcape exactly)

**Comment by lestcape** [comment]
If was not clear yet, we want to know how to detect the **Visible Type**, of the menuItem, and not the **Real Type**.

![check](https://user-images.githubusercontent.com/1389572/40198069-f04e61d2-59da-11e8-8712-0a1ae3531355.png)

**Comment by lestcape** [comment]
@spectrejie like i see you have the ultimate version of IntelliJ. So, if you paid for it, open an issue in his side to inform about the improper menu items that are exported to all globals menus in linux in general. This is the only gnome shell implementation of the global menu, but the @rilian-la-te implementation is the implementation of Mate, XFCE... and whatever where you can load a vala and gtk applet. Also this won't work on KDE as the only tools to extract the information from a java application is jayatana currently.

The problem it's a decision in the implementation of IntelliJ menus, that create custom menu-items that are **NOT** standards. If there are not way to differentiate it, will be not possible find a solution.

Anyway I'm in disagree with create specific patches to specific applications, because in that way we never will be ending. Apparently @rilian-la-te want to also do that, but it need help from sure, as this is an specific decision of the jetbrains developers and really not a bug in jayatana or here.

From another side, I'don't develop a paid application and also i don't want donation, so, I'm against to help to any paid applications, more if they don't care. I know they have a community version and this is the only thing that make me thinking in help, but just help in case they want, not to fix his problems. I don't use IntelliJ, i really use eclipse.

Just for add references to several issues they have about this characteristics in the net:
https://www.reddit.com/r/kde/comments/67mnfq/global_menu_in_plasma_59_with_java_intellij_and/
https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000060530--Ubuntu-No-global-menu-with-Jayatana
https://intellij-support.jetbrains.com/hc/en-us/community/posts/206559509-Ubuntu-s-global-menu-
https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000633964-Global-menu-Jayataana-doesn-t-work

So, i recommend you fire a bug against the offending applications, this is **all jetbrains products** and not here.

**Comment by lestcape** [comment]
@rilian-la-te but this is really not a fault of jayatana and really not a fault of vala-panel. So, i don't think you need to find a solution to all inventions that someone made, because It will be absurd. If they want to create an specific set of menu items is fine, but you don't need to be a magician, just because one application not work and the reason is that his authors decide to do the thing in a personal way (this then need to be his personal problem and not a problem of jayatana or your applet). They are who create the problem and they can fixed it if  they want, so let users to know from who is the fault is more than enough.

**Comment by lestcape** [comment]
For example: If they check for JAVA_TOOL_OPTIONS instead of for the specific session name, they can easy apply the same solution they apply to unity to all platform where and when the jayatana is loaded. This is really an easy solution in his side. Also a more general one, than just check for the xsession environment variable.

**Comment by lestcape** [comment]
I leave some comments to Alexey Ushakov https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000060530--Ubuntu-No-global-menu-with-Jayatana?page=1#community_comment_360000196984

He was who create the specific patch for unity desktop. So, he can extends it to all...

**Comment by trespasserw** [comment]
@lestcape sorry for the late reply.

I know about JAyatana and (roughly) how it works. I was trying to tell that in Swing, the difference between JMenuItem and JCheckBoxMenuItem is minimal. The latter carries a state bit along it, when that bit isn't set - there is no difference at all, and when that bit is set - the only difference is a "check mark" on the item.

But you better discuss that with Alexey.

**Comment by rilian-la-te** [comment]
@trespasserw but JAyatan does not know, whether state is needed or not, and assumed than state is required for DBusMenu, and we in client applets en up with all checkboxes (as on @lestcape screenshot).

**Comment by lestcape** [comment]
@trespasserw not worry and thanks, like @rilian-la-te said is not useful to us the aesthetics of java swing components. We don't use java in the client side.

The problem is that, we are painting in a different toolkit, but we used the information that jayatana provide. So, we only used jayatana and java swing to detect types (in the JetBrains case, wrong types) and the information in general, but we really can not used java swing components in our client side (the desktop). Instead, we are forced to used the desktop specific toolkit, because we are extensions of the desktop and of course, linux desktops are not builds with java components.

For what i see, all will be fixed with an easy change in your side and is possible to JetBrains do it, so i don't think anymore that we need to understand somethings. The decision is in your side. 

I speak with Alexy, because he was who make that to only support Unity desktop, but nothing special, i think if he make this intentionally specific, he is who need to take the time to assess whether or not it may be more general. 

In my opinion, trying to understand your code to forced it from our side, is not the way to go. So, thanks to take some time here trying to explain us how it work, personally i don't think anymore that this will really help, because all is just decisions you need to take from your side and nothing more.
