### ISSUE TITLE
Keep getting errros when using the extension

### ISSUE THREAD

**Issue by Waelwindows** [lestcape/Gnome-Global-AppMenu#96]
When I ever use the extension, I'm always bombarded with the error "err450 is not a valid value for enumeration Weight"

**Comment by lestcape** [comment]
As you need to suppose, this is something that not occurs to others (I can not reproduced it). So, please give some details...

1- Gnome Shell version?
2- Distro and version?
3- This occurs to you with the last version of the extension that was downloaded from here?
4- This error occurs also if you only have this extension installed?
5- Where you see that error?
6- What happen when you see the error with the extension?
7- If you do not make anything the error stop also or continues happens for a long time?
8- In which contexts is the error shown?
9- Which window has the focus when the error occurs?
10- Do you have installed what packages?
11- What changes you do in the extension settings?

**Comment by lestcape** [comment]
I think it can also be related with the theme that you have installed.

**Comment by Waelwindows** [comment]
GNOME Shell 3.28.1
Ubuntu 18.04
Yes the latest version
No, this error only occurs when the extension is enabled
In my notifications center
Nothing out of the ordinary happens, the extension seems to work fine, however there's some weird gap between "Activities" and the start of the global menu's menus
It's shown all the time, even when you clear it
I was running firefox, but the error occurs with any application running
I have 
- OpenWeather
- Pixel Saver
- Suspend button
- and the ubuntu default extensions

**Comment by lestcape** [comment]
Yes, like the last comment, the problem seem to be a theme issue.
Can you tell me what theme you have?
The shell-theme and also gtk-theme. Anyway, apparently this is because the shell-theme.

The problem is localized in this area:
https://github.com/lestcape/Gnome-Global-AppMenu/blob/master/gnomeGlobalAppMenu%40lestcape/configurableMenus.js#L2580-L2632

And is relate with some properties that are needed to draw the application name, but the theme that you use have not this properties.

As a workaround, you can disable the "**Show a linear gradient effect in the application name**" in the settings and this will fix the problem, but if i have your theme, i can find why this happens and prevent the crash also when the theme not provide what the global menu need to be working. Just i have not idea currently about the specific cause.

**Comment by Waelwindows** [comment]
I'm currently using communitheme, if that's what you're talking about
