### ISSUE TITLE
Use GNOME extensions manager

### ISSUE THREAD

**Issue by chriskuech** [lestcape/Gnome-Global-AppMenu#97]
According to https://extensions.gnome.org/extension/1250/gnome-global-application-menu/, this extension is not being updated in the standard distributor.  Please distribute through extensions.gnome.org

**Comment by lestcape** [comment]
Hi @chriskuech. I'm just develop an extension here and i have not intention to distribute anything, but you can do it if you want :). Just take in consideration that this mean, you need to active participle in the release process, not just take one thing from here and put down in other place and forget this happens, because this will not really help for more than one month.

In my personal criteria, I disagree to do that, because i have really big disappoint with what was occurs to all my extensions in cinnamon. I put all extensions in the spice website of Mint to be distribute. From one day to another all extensions there was forked by the hoster (Mint).

So, not thanks, this will not happens to me again. The user that will want to interact in the developer process, here is the place to do it so... sorry.

Also please see: https://github.com/lestcape/Gnome-Global-AppMenu/issues/26
